service: nest-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  profile: freeaws_sls
  region: us-east-1

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
