service: nest-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  profile: freeaws_sls
  region: us-east-1
  environment:
    DATABASE_NAME: freeaws
    DATABASE_HOST: rds-database-freeaws.co3pfw2peihx.us-east-1.rds.amazonaws.com
    DATABASE_PORT: 5432
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
